version: '3.1'

services:  
    mysql:
        container_name: mysql
        image: mysql
        env_file: 
            - .env
        volumes:
            - mysql-data:/var/lib/mysql
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always

    adminer:
        container_name: adminer
        image: adminer
        ports:
          - "8080:8080"
        restart: always 


volumes:
    mysql-data:
