version: '3.1'

services:
    postgres:
        image: postgres:latest
        env_file: 
            - .env
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            DB_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        restart: always
  
    mysql:
        image: mysql:latest
        env_file: 
            - .env
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always

    adminer:
        image: adminer:latest
        ports:
          - 8080:8080
        restart: always 