version: '3.1'

services:
    postgres:
        container_name: postgres
        image: postgres
        env_file: 
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            DB_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        restart: always
  
    mysql:
        container_name: mysql
        image: mysql
        env_file: 
            - .env
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always

    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        restart: always

    adminer:
        container_name: adminer
        image: adminer
        ports:
          - "8081:8080"
        restart: always 

volumes:
    postgres-data:
    mysql-data: